create table member
(
id bigint generated by default as identity,
email varchar(255),
passwd varchar(255),
birth varchar(11),
name varchar(255),
phone varchar(14),
nickname varchar(255),
createDate datetime,
gender varchar(2),
primary key (id)
);